# -*- coding: utf-8 -*-
"""GDSC Hands-On

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o4cowMWcZayvhnIGITvJMgKG0gOaLT3B
"""

print('Nama: Nadhira Azzahra')
print('Jurusan: FTI')
print('Alasan ingin masuk GDSC: Pengen nambah pengalaman baru dan pengen tahu seputar developing')