# -*- coding: utf-8 -*-
"""Handson_1_GDSC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlBu5IAJjw0msBm8JuzeG9ad81dRved0
"""

Identitas = ["Kahfi Rizky Kosasih","Matematika","Saya ingin bergabung dengan GDSC sebagai langkah awal untuk mencapai tujuan yang saya impikan."]
Index = ["Nama: ", "Jurusan: ", "Alasan ingin masuk GDSC: "]

for i in range (len(Identitas)):
  print(Index[i], end = "") ; print(Identitas[i])