# -*- coding: utf-8 -*-
"""Identitas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BN5-csHG1jj7qwoyZlJVQ8t_PgeB2o5z
"""

print("Nama : Ang, Johan Nicholas")
print("Jurusan : STEI")
print("Alasan ingin masuk GDSC : ingin mengembangkan kemampuan programming.")