print("-"*175)
print("Halo salam kenal, kalian bisa mengenal lebih banyak tentang aku di bawah ini:")
print(f"Nama: Alvaro Austin")
print(f"Jurusan: Ilmu Komputer")
print(f"Universitas: Universitas Indonesia")
print(f"Alasan ingin masuk GDSC: Saya ingin menambah pengalaman saya tidak hanya dalam programming namun juga berbagai hal. Menurut saya GDSC ITB adalah tempat yang cocok untuk ini")
print(f"Game favorit: Dota2")
print("-"*175)
