# -*- coding: utf-8 -*-
"""FahrizalWijanarkoAmroe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-TmG_THrS80k6CDguR5hYF7VHV-RRzZ
"""

print("Nama : Fahrizal Wijanarko Amroe \nJurusan : Teknik Informatika \nAlasan : Ingin menambah softskill dan hardskill")