str (print("Form Pendaftaran GDSC"))
Nama = str (input("Nama: "))
Jurusan = str (input("Jurusan: "))
Alasan = str (input("Alasan ingin masuk GDSC: "))
str (print("Data Terkirim"))
str (print("Lampiran:"))
print ("Nama: ", Nama)
print ("Jurusan: ", Jurusan)
print ("Alasan ingin masuk GDSC: ", Alasan)
