Introduksi      := Identitas
Deskripsi       := Nama Jurusan Alasan

Nama            := Fikri Yudhistira
Jurusan         := Matematika
Alasan          := Saya mengikuti GDSC demi mempelajari software development untuk platform Android.

$(Introduksi): $(Deskripsi) ;

%:
	@echo '$@	: $($@)'
