# -*- coding: utf-8 -*-
"""identitas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0ujJtASBgQvD48sQuv80Eku17TIA2Q7
"""

name = "Tantio Bagus Cahyono"
major = "Matematika"
Alasan = "Untuk menambah pengetahuan dan skill pemrograman serta menambah relasi"

print("Nama : ",name)
print("Jurusan : ",major)
print("Alasan ingin masuk GDSC : ",Alasan)